=== matkoman-py/xml-veb-servisi/OfficialsApplication/src/main/resources/static/xsd/PotvrdaOVakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.ftn.uns.ac.rs/potvrda_o_vakcinaciji"
    xmlns:pot="www.ftn.uns.ac.rs/potvrda_o_vakcinaciji">
    <xs:element name="Potvrda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sifra_potvrde" type="xs:string"/>
                <xs:element name="pacijent" type="pot:TPacijent"/>
                <xs:element name="Vakcinacija_info" type="pot:TVakcinacija"/>
                <xs:element name="Qr_kod" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDozaInfo">
        <xs:sequence>
            <xs:element name="Datum_vakcine" type="xs:date"/>
            <xs:element name="Serija_vakcine" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPacijent">
        <xs:sequence>
            <xs:element name="Ime_i_prezime" type="xs:string"/>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="Pol">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Musko"/>
                        <xs:enumeration value="Zensko"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Jmbg">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="13"/>
                        <xs:pattern value="\d{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="Prva_doza" type="pot:TDozaInfo"/>
            <xs:element minOccurs="0" name="Druga_doza" type="pot:TDozaInfo"/>
            <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
            <xs:element name="Naziv_vakcine" type="xs:string"/>
            <xs:element name="Datum_izdavanja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== matkoman-py/xml-veb-servisi/KT1/XMLSeme/PotvrdaOVakcinaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns="www.ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.ftn.uns.ac.rs/potvrda_o_vakcinaciji PotvrdaOVakcinaciji.xsd">
    <Sifra_potvrde>23532</Sifra_potvrde>
    <pacijent>
        <Ime_i_prezime>Petar Markovic</Ime_i_prezime>
        <Datum_rodjenja>1999-10-29</Datum_rodjenja>
        <Pol>Musko</Pol>
        <Jmbg>2910999730020</Jmbg>
    </pacijent>
    <Vakcinacija_info>
        <Prva_doza>
            <Datum_vakcine>2021-03-04</Datum_vakcine>
            <Serija_vakcine>EW2243</Serija_vakcine>
        </Prva_doza>
        <Zdravstvena_ustanova>Dom zdravlja Novo Naselje</Zdravstvena_ustanova>
        <Naziv_vakcine>Pfizer BionTech</Naziv_vakcine>
        <Datum_izdavanja>2021-05-04</Datum_izdavanja>
    </Vakcinacija_info>
    <Qr_kod>NSw2LDQsMiw0MjMsNDIzLA==</Qr_kod>
</Potvrda>
