=== matkoman-py/xml-veb-servisi/OfficialsApplication/src/main/resources/static/xsd/ZeleniSertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.ftn.uns.ac.rs/zelenisertifikat"
    xmlns:zel="www.ftn.uns.ac.rs/zelenisertifikat" id="asdasda"
    xmlns:z="www.ftn.uns.ac.rs/zelenisertifikat">

    <xs:element name="zeleni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="qr_kod">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="4"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj_sertifikata" type="z:TBrojSertifikata"> </xs:element>
                <xs:element name="datum_izdavanja" type="xs:dateTime"/>
                <xs:element name="podaci_o_pacijentu" type="zel:TPacijent"/>
                <xs:element maxOccurs="unbounded" name="podaci_o_vakcinaciji"
                    type="zel:TVakcinacija"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string" use="required"/>
            <xs:attribute fixed="pred:parentTo" name="rel" type="xs:string"/>
            <xs:attribute name="href" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPacijent">
        <xs:sequence>
            <xs:element name="ime_prezime" type="z:TImeIPrezime"> </xs:element>
            <xs:element name="pol">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Musko"/>
                        <xs:enumeration value="Zensko"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum_rodjenja" type="xs:date"/>
            <xs:element name="jmbg" type="z:TJmbg"> </xs:element>
            <xs:element name="broj_pasosa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="13"/>
                        <xs:pattern value="\d+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="doza" type="xs:positiveInteger"/>
            <xs:element name="tip" type="xs:string"/>
            <xs:element name="proizvodjac_serija" type="xs:string"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="zdravstvena_ustanova" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TImeIPrezime">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:ime_i_prezime"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TJmbg">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:jmbg"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TBrojSertifikata">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:broj_sertifikata"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== matkoman-py/xml-veb-servisi/OfficialsApplication/src/main/resources/static/xsd/ZeleniSertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<zel:zeleni_sertifikat about="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zel="http://www.ftn.uns.ac.rs/zelenisertifikat" xsi:schemaLocation="http://www.ftn.uns.ac.rs/zelenisertifikat ZeleniSertifikat.xsd ">
  <zel:qr_kod>zel:qr_kod</zel:qr_kod>
  <zel:broj_sertifikata datatype="xs:string" property="pred:broj_sertifikata">zel:broj_sertifikata</zel:broj_sertifikata>
  <zel:datum_izdavanja datatype="xs:dateTime" property="pred:datum">2001-12-31T12:00:00</zel:datum_izdavanja>
  <zel:podaci_o_pacijentu>
    <zel:ime_prezime datatype="xs:string" property="pred:ime_i_prezime">zel:ime_prezime</zel:ime_prezime>
    <zel:pol>Musko</zel:pol>
    <zel:datum_rodjenja>2001-01-01</zel:datum_rodjenja>
    <zel:jmbg datatype="xs:string" property="pred:jmbg">zel:jmbg</zel:jmbg>
    <zel:broj_pasosa>1234322314323</zel:broj_pasosa>
  </zel:podaci_o_pacijentu>
  <zel:podaci_o_vakcinaciji>
    <zel:doza>1</zel:doza>
    <zel:tip>zel:tip</zel:tip>
    <zel:proizvodjac_serija>zel:proizvodjac_serija</zel:proizvodjac_serija>
    <zel:datum>2001-01-01</zel:datum>
    <zel:zdravstvena_ustanova>zel:zdravstvena_ustanova</zel:zdravstvena_ustanova>
  </zel:podaci_o_vakcinaciji>
</zel:zeleni_sertifikat>
