=== matkoman-py/xml-veb-servisi/KT1/XMLSeme/Izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.ftn.uns.ac.rs/Izvestaj_o_imunizaciji" version="1.1"
    xmlns:izv="www.ftn.uns.ac.rs/Izvestaj_o_imunizaciji">

    <xs:element name="Izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Period" type="izv:TPeriod"/>
                <xs:element name="Broj_podnetih_interesovanja" type="xs:positiveInteger"/>
                <xs:element name="Zeleni_sertifikat_info" type="izv:TZeleni_sertifikat"/>
                <xs:element name="Doza_info" type="izv:TDoza_info"/>
                <xs:element name="Proizvodjaci_info" type="izv:TProizvodjaci_info"/>
                <xs:element name="Datum_izdavanja" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="redni_broj" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPeriod">
        <xs:sequence>
            <xs:element name="Datum_od" type="xs:date"/>
            <xs:element name="Datum_do" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TZeleni_sertifikat">
        <xs:sequence>
            <xs:element name="Broj_primljenih_zahteva" type="xs:nonNegativeInteger"/>
            <xs:element name="Broj_izdatih_sertifikata" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDoza_info">
        <xs:sequence>
            <xs:element name="Broj_datih_doza" type="xs:nonNegativeInteger"/>
            <xs:element name="Broj_date_prve_doze" type="xs:nonNegativeInteger"/>
            <xs:element name="Broj_date_druge_doze" type="xs:positiveInteger"/>
            <xs:element name="Broj_date_trece_doze" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TProizvodjaci_info">
        <xs:sequence>
            <xs:element name="Broj_doza_Pfizer_BioNTech" type="xs:nonNegativeInteger"/>
            <xs:element name="Broj_doza_Sinopharm" type="xs:nonNegativeInteger"/>
            <xs:element name="Broj_doza_SputnikV" type="xs:nonNegativeInteger"/>
            <xs:element name="Broj_doza_AstraZeneca" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== matkoman-py/xml-veb-servisi/OfficialsApplication/src/main/resources/static/xsd/Izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<izv:Izvestaj_o_imunizaciji about="" id="1" xmlns:izv="http://www.ftn.uns.ac.rs/Izvestaj_o_imunizaciji" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/Izvestaj_o_imunizaciji Izvestaj_o_imunizaciji.xsd ">
  <izv:Period>
    <izv:Datum_od datatype="xs:date" property="pred:datum_od">2001-01-01</izv:Datum_od>
    <izv:Datum_do datatype="xs:date" property="pred:datum_do">2001-01-01</izv:Datum_do>
  </izv:Period>
  <izv:Broj_podnetih_interesovanja datatype="xs:positiveInteger" property="pred:broj_interesovanja">1</izv:Broj_podnetih_interesovanja>
  <izv:Zeleni_sertifikat_info>
    <izv:Broj_primljenih_zahteva>0</izv:Broj_primljenih_zahteva>
    <izv:Broj_izdatih_sertifikata>0</izv:Broj_izdatih_sertifikata>
  </izv:Zeleni_sertifikat_info>
  <izv:Doza_info>
    <izv:Broj_datih_doza>0</izv:Broj_datih_doza>
    <izv:Broj_date_prve_doze>0</izv:Broj_date_prve_doze>
    <izv:Broj_date_druge_doze>1</izv:Broj_date_druge_doze>
    <izv:Broj_date_trece_doze>0</izv:Broj_date_trece_doze>
  </izv:Doza_info>
  <izv:Proizvodjaci_info>
    <izv:Broj_doza_Pfizer_BioNTech>0</izv:Broj_doza_Pfizer_BioNTech>
    <izv:Broj_doza_Sinopharm>0</izv:Broj_doza_Sinopharm>
    <izv:Broj_doza_SputnikV>0</izv:Broj_doza_SputnikV>
    <izv:Broj_doza_AstraZeneca>0</izv:Broj_doza_AstraZeneca>
  </izv:Proizvodjaci_info>
  <izv:Datum_izdavanja datatype="xs:dateTime" property="pred:datum">2001-12-31T12:00:00</izv:Datum_izdavanja>
</izv:Izvestaj_o_imunizaciji>

=== matkoman-py/xml-veb-servisi/KT1/XMLSeme/Izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj_o_imunizaciji xmlns="www.ftn.uns.ac.rs/Izvestaj_o_imunizaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.ftn.uns.ac.rs/Izvestaj_o_imunizaciji file:/D:/Faks/CetvrtaDina/XMLVebServisi/KT1/XMLSeme/Izvestaj_o_imunizaciji.xsd" redni_broj="50">
    <Period>
        <Datum_od>2006-05-04</Datum_od>
        <Datum_do>2006-05-04</Datum_do>
    </Period>
    <Broj_podnetih_interesovanja>50</Broj_podnetih_interesovanja>
    <Zeleni_sertifikat_info>
        <Broj_primljenih_zahteva>50</Broj_primljenih_zahteva>
        <Broj_izdatih_sertifikata>50</Broj_izdatih_sertifikata>
    </Zeleni_sertifikat_info>
    <Doza_info>
        <Broj_datih_doza>50</Broj_datih_doza>
        <Broj_date_prve_doze>50</Broj_date_prve_doze>
        <Broj_date_druge_doze>50</Broj_date_druge_doze>
        <Broj_date_trece_doze>50</Broj_date_trece_doze>
    </Doza_info>
    <Proizvodjaci_info>
        <Broj_doza_Pfizer_BioNTech>50</Broj_doza_Pfizer_BioNTech>
        <Broj_doza_Sinopharm>50</Broj_doza_Sinopharm>
        <Broj_doza_SputnikV>50</Broj_doza_SputnikV>
        <Broj_doza_AstraZeneca>50</Broj_doza_AstraZeneca>
    </Proizvodjaci_info>
    <Datum_izdavanja>2006-05-04</Datum_izdavanja>
</Izvestaj_o_imunizaciji>
