=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/Korisnik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.ftn.uns.ac.rs/korisnik"
           xmlns:kor="http://www.ftn.uns.ac.rs/korisnik">

    <xs:element name="korisnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drzavljanstvo" type="xs:string"/>
                <xs:element name="jmbg" type="xs:string"/>
                <xs:element name="broj_pasosa" type="xs:string"/>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="ime_roditelja" type="xs:string"/>
                <xs:element name="pol">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="muski"/>
                            <xs:enumeration value="zenski"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="datum_rodjenja" type="xs:date"/>
                <xs:element name="mesto_rodjenja" type="xs:string"/>
                <xs:element name="adresa" type="xs:string"/>
                <xs:element name="mesto" type="xs:string"/>
                <xs:element name="grad" type="xs:string"/>
                <xs:element name="fiksni_telefon" type="xs:string"/>
                <xs:element name="mobilni_telefon" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="sifra" type="xs:string"/>
                <xs:element name="rola">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="gradjanin"/>
                            <xs:enumeration value="sluzbenik"/>
                            <xs:enumeration value="zdravstveni_radnik"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== matkoman-py/xml-veb-servisi/OfficialsApplication/src/main/resources/static/xsd/korisnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<kor:korisnik xmlns:kor="http://www.ftn.uns.ac.rs/korisnik" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/korisnik Korisnik.xsd ">
  <kor:drzavljanstvo>Srpsko</kor:drzavljanstvo>
  <kor:jmbg>2910999730020</kor:jmbg>
  <kor:broj_pasosa>9321321</kor:broj_pasosa>
  <kor:ime>Petar</kor:ime>
  <kor:prezime>Markovic</kor:prezime>
  <kor:ime_roditelja>Zoran</kor:ime_roditelja>
  <kor:pol>muski</kor:pol>
  <kor:datum_rodjenja>1999-10-29</kor:datum_rodjenja>
  <kor:mesto_rodjenja>Nis</kor:mesto_rodjenja>
  <kor:adresa>Vladike Cirica 5</kor:adresa>
  <kor:mesto>Novi Sad</kor:mesto>
  <kor:grad>Novi Sad</kor:grad>
  <kor:fiksni_telefon>021493103</kor:fiksni_telefon>
  <kor:mobilni_telefon>0692910099</kor:mobilni_telefon>
  <kor:email>radnik@gmail.com</kor:email>
  <kor:sifra>petar123</kor:sifra>
  <kor:rola>sluzbenik</kor:rola>
</kor:korisnik>
