=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/PotvrdaOVakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji"
    xmlns:pot="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji"
    xmlns:pred="http://www.ftn.uns.ac.rs/predicate">
    <xs:element name="Potvrda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sifra_potvrde" type="xs:string"/>
                <xs:element name="pacijent" type="pot:TPacijent"/>
                <xs:element name="Vakcinacija_info" type="pot:TVakcinacija"/>
                <xs:element name="Qr_kod" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string" use="required"/>
            <xs:attribute fixed="pred:parentTo" name="rel" type="xs:string"/>
            <xs:attribute name="href" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDozaInfo">
        <xs:sequence>
            <xs:element name="Datum_vakcine" type="xs:date"/>
            <xs:element name="Serija_vakcine" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPacijent">
        <xs:sequence>
            <xs:element name="Ime_i_prezime" type="pot:TImeIPrezime"/>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="Pol">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Musko"/>
                        <xs:enumeration value="Zensko"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Jmbg" type="pot:TJmbg"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="Prva_doza" type="pot:TDozaInfo"/>
            <xs:element minOccurs="0" name="Druga_doza" type="pot:TDozaInfo"/>
            <xs:element name="Zdravstvena_ustanova" type="pot:TZdravstvenaUstanova"/>
            <xs:element name="Naziv_vakcine" type="pot:TNazivVakcine"/>
            <xs:element name="Datum_izdavanja" type="pot:TDatumIzdavanja"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TNazivVakcine">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:naziv_vakcine"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TZdravstvenaUstanova">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:zdravstvena_ustanova"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TImeIPrezime">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:ime_i_prezime"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TJmbg">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:jmbg"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TDatumIzdavanja">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="property" use="required" fixed="pred:datum"/>
                <xs:attribute name="datatype" use="required" fixed="xs:date"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/pot.xml
<?xml version="1.0" encoding="UTF-8"?>
<pot:Potvrda about="" xmlns:pot="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji PotvrdaOVakcinaciji.xsd ">
  <pot:Sifra_potvrde>pot:Sifra_potvrde</pot:Sifra_potvrde>
  <pot:pacijent>
    <pot:Ime_i_prezime datatype="xs:string" property="pred:ime_i_prezime">pot:Ime_i_prezime</pot:Ime_i_prezime>
    <pot:Datum_rodjenja>2001-01-01</pot:Datum_rodjenja>
    <pot:Pol>Musko</pot:Pol>
    <pot:Jmbg datatype="xs:string" property="pred:jmbg">pot:Jmbg</pot:Jmbg>
  </pot:pacijent>
  <pot:Vakcinacija_info>
    <pot:Prva_doza>
      <pot:Datum_vakcine>2001-01-01</pot:Datum_vakcine>
      <pot:Serija_vakcine>pot:Serija_vakcine</pot:Serija_vakcine>
    </pot:Prva_doza>
    <pot:Zdravstvena_ustanova datatype="xs:string" property="pred:zdravstvena_ustanova">pot:Zdravstvena_ustanova</pot:Zdravstvena_ustanova>
    <pot:Naziv_vakcine datatype="xs:string" property="pred:naziv_vakcine">pot:Naziv_vakcine</pot:Naziv_vakcine>
    <pot:Datum_izdavanja datatype="xs:date" property="pred:datum">2001-01-01</pot:Datum_izdavanja>
  </pot:Vakcinacija_info>
  <pot:Qr_kod>pot:Qr_kod</pot:Qr_kod>
</pot:Potvrda>
