=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/Saglasnost.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/Saglasnost"
    xmlns:sag="http://www.ftn.uns.ac.rs/Saglasnost" xmlns:pred="http://www.ftn.uns.ac.rs/predicate">

    <xs:element name="Saglasnost">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Drzavljanstvo" type="sag:TDrzavljanstvo"/>
                <xs:element name="Podaci_o_pacijentu" type="sag:TPacijent"/>
                <xs:element name="Evidencija_o_vakcinaciji" type="sag:TEvidencija" minOccurs="0"
                    nillable="true"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string" use="required"/>
            <xs:attribute name="href" type="xs:string"/>
            <xs:attribute fixed="pred:fromInteresovanje" name="rel" type="xs:string" use="required"
            />
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDrzavljanstvo">
        <xs:choice>
            <xs:element name="JMBG" type="xs:string"> </xs:element>
            <xs:sequence>
                <xs:element name="Naziv" type="xs:string" form="qualified"/>
                <xs:element name="Broj_pasosa_EBS" type="xs:string"> </xs:element>
            </xs:sequence>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TPacijent">
        <xs:sequence>
            <xs:element name="Prezime" type="sag:TPrezime"/>
            <xs:element name="Ime" type="sag:TIme"/>
            <xs:element name="Ime_roditelja" type="xs:string"/>
            <xs:element name="Pol" type="sag:TPol"/>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="Mesto_rodjenja" type="xs:string"/>
            <xs:element name="Adresa" type="sag:TAdresa"/>
            <xs:element name="Kontakt" type="sag:TKontakt"/>
            <xs:element name="Radni_status" type="sag:TRadni_status"/>
            <xs:element name="Zanimanje" type="sag:TZanimanje" nillable="false"/>
            <xs:element name="Socijalna_zastita_info" type="sag:TSocijalna_zastita"/>
            <xs:element name="Izjava_saglasnosti" type="sag:TIzjava_saglasnosti"/>
            <xs:element name="Datum" type="sag:TDatumIzdavanja"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TPol">
        <xs:restriction base="xs:string">
            <xs:enumeration value="muski"/>
            <xs:enumeration value="zenski"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Ulica_i_broj" type="xs:string"/>
            <xs:element name="Mesto" type="xs:string"/>
            <xs:element name="Opstina" type="sag:TOpstina"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TKontakt">
        <xs:sequence>
            <xs:element name="Fiksni" type="xs:string"> </xs:element>
            <xs:element name="Mobilni" type="xs:string"> </xs:element>
            <xs:element name="Email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9_.+\-]+@[a-zA-Z0-9\-]+.[a-zA-Z0-9\-.]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TRadni_status">
        <xs:restriction base="xs:string">
            <xs:enumeration value="zaposlen"/>
            <xs:enumeration value="nezaposlen"/>
            <xs:enumeration value="penzioner"/>
            <xs:enumeration value="ucenik"/>
            <xs:enumeration value="student"/>
            <xs:enumeration value="dete"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TZanimanje">
        <xs:restriction base="xs:string">
            <xs:enumeration value="zdravstvena_zastita"/>
            <xs:enumeration value="socijalna_zastita"/>
            <xs:enumeration value="prosveta"/>
            <xs:enumeration value="MUP"/>
            <xs:enumeration value="vojska_rs"/>
            <xs:enumeration value="drugo"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TSocijalna_zastita">

        <xs:sequence>
            <xs:element name="Koristi_zastitu">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="da"/>
                        <xs:enumeration value="ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Naziv_opstina_sedista" type="xs:string" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TIzjava_saglasnosti">
        <xs:sequence>
            <xs:element name="Saglasan">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="saglasan sam"/>
                        <xs:enumeration value="nisam saglasan"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Naziv_leka" type="xs:string" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TEvidencija">
        <xs:sequence>
            <xs:element name="Naziv_ustanove" type="sag:TZdravstvenaUstanova"/>
            <xs:element name="Vakcinacijski_punkt" type="xs:string"/>
            <xs:element name="Podaci_lekar" type="xs:string"/>
            <xs:element name="Vakcinacija" type="sag:TVakcinacija" minOccurs="0" nillable="true"/>
            <xs:element name="Revakcinacija" type="sag:TVakcinacija" minOccurs="0" nillable="true"/>
            <xs:element name="Privremene_kontraindikacije" type="xs:string" nillable="true"
                minOccurs="0"/>
            <xs:element name="Odluka_komisije" type="xs:string" nillable="true" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="Naziv_vakcine" type="sag:TNazivVakcine"/>
            <xs:element name="Datum_vakcinacije" type="xs:date"/>
            <xs:element name="Ekstremitet" type="xs:string"> </xs:element>
            <xs:element name="Lot" type="xs:string"/>
            <xs:element name="Proizvodjac" type="xs:string"/>
            <xs:element name="Nezeljena_reakcija" type="xs:string" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOpstina">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:opstina"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TIme">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:ime"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TPrezime">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:prezime"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TNazivVakcine">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:naziv_vakcine"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TZdravstvenaUstanova">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:zdravstvena_ustanova"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TDatumIzdavanja">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="property" use="required" fixed="pred:datum"/>
                <xs:attribute name="datatype" use="required" fixed="xs:date"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== matkoman-py/xml-veb-servisi/KT1/XMLSeme/Saglasnost.xml
<?xml version="1.0" encoding="UTF-8"?>
<sag:Saglasnost xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:sag="www.ftn.uns.ac.rs/Saglasnost"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.ftn.uns.ac.rs/Saglasnost saglasnost.xsd">
    <sag:Drzavljanstvo>
        <sag:JMBG>2910999730020</sag:JMBG>
    </sag:Drzavljanstvo>
    <sag:Podaci_o_pacijentu>
        <sag:Prezime>Markovic</sag:Prezime>
        <sag:Ime>Petar</sag:Ime>
        <sag:Ime_roditelja>Zoran</sag:Ime_roditelja>
        <sag:Pol>muski</sag:Pol>
        <sag:Datum_rodjenja>1999-10-29</sag:Datum_rodjenja>
        <sag:Mesto_rodjenja>Nis</sag:Mesto_rodjenja>
        <sag:Adresa>
            <sag:Ulica_i_broj>Vladike Cirica 5</sag:Ulica_i_broj>
            <sag:Mesto>Novi Sad</sag:Mesto>
            <sag:Opstina>Novi sad</sag:Opstina>
        </sag:Adresa>
        <sag:Kontakt>
            <sag:Fiksni>021493103</sag:Fiksni>
            <sag:Mobilni>0692910099</sag:Mobilni>
            <sag:Email>petarns99@gmail.com</sag:Email>
        </sag:Kontakt>
        <sag:Radni_status>zaposlen</sag:Radni_status>
        <sag:Socijalna_zastita_info>
            <sag:Koristi_zastitu>da</sag:Koristi_zastitu>
        </sag:Socijalna_zastita_info>
        <sag:Izjava_saglasnosti>
            <sag:Saglasan>saglasan sam</sag:Saglasan>
        </sag:Izjava_saglasnosti>
        <sag:Datum>2021-05-04</sag:Datum>
    </sag:Podaci_o_pacijentu>
    <sag:Evidencija_o_vakcinaciji>
        <sag:Naziv_ustanove>Dom zdravlja Novo Naselje</sag:Naziv_ustanove>
        <sag:Vakcinacijski_punkt>Punkt broj 1</sag:Vakcinacijski_punkt>
        <sag:Podaci_lekar>Marko Markovic 0643543232</sag:Podaci_lekar>
        <sag:Vakcinacija>
            <sag:Naziv_vakcine>Pfizer BionTech</sag:Naziv_vakcine>
            <sag:Datum_vakcinacije>2021-06-04</sag:Datum_vakcinacije>
            <sag:Ekstremitet>lr</sag:Ekstremitet>
            <sag:Lot>Lot 1</sag:Lot>
            <sag:Proizvodjac>Pfizer</sag:Proizvodjac>
        </sag:Vakcinacija>
        <sag:Revakcinacija>
            <sag:Naziv_vakcine>Pfizer BionTech</sag:Naziv_vakcine>
            <sag:Datum_vakcinacije>2021-06-24</sag:Datum_vakcinacije>
            <sag:Ekstremitet>lr</sag:Ekstremitet>
            <sag:Lot>Lot 2</sag:Lot>
            <sag:Proizvodjac>Pfizer</sag:Proizvodjac>
        </sag:Revakcinacija>
    </sag:Evidencija_o_vakcinaciji>
</sag:Saglasnost>
