=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/ZahtevZelenogSertifikata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata"
    xmlns:zzs="www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata">
    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element form="qualified" name="Podnosilac_zahteva"
                    type="zzs:TInformacije_o_podnosiocu"/>
                <xs:element name="Informacije_o_zahtevu" type="zzs:TInformacije_o_zahtevu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TInformacije_o_podnosiocu">
        <xs:sequence>
            <xs:element name="Ime_i_prezime" type="xs:string"/>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="Pol">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Musko"/>
                        <xs:enumeration value="Zensko"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Jedinstveni_maticni_broj_gradjana">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="13"/>
                        <xs:pattern value="\d{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Broj_pasosa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{10}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TInformacije_o_zahtevu">
        <xs:sequence>
            <xs:element name="Razlog">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="0"/>
                        <xs:maxLength value="300"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Mesto" type="xs:string"/>
            <xs:element name="Datum_izdavanja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<zzs:zahtev xmlns:zzs="http://www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata"
 xmlns:pred="http://www.ftn.uns.ac.rs/predicate"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata ZahtevZelenogSertifikata.xsd" about="">
    <zzs:Podnosilac_zahteva>
        <zzs:Ime_i_prezime property="pred:ime_i_prezime" datatype="xs:string">Petar Markovic</zzs:Ime_i_prezime>
        <zzs:Datum_rodjenja>1999-10-29</zzs:Datum_rodjenja>
        <zzs:Pol>Musko</zzs:Pol>
        <zzs:Jedinstveni_maticni_broj_gradjana property="pred:jmbg" datatype="xs:string">29101999730020</zzs:Jedinstveni_maticni_broj_gradjana>
        <zzs:Broj_pasosa property="pred:broj_pasosa" datatype="xs:string">100321032</zzs:Broj_pasosa>
    </zzs:Podnosilac_zahteva>
    <zzs:Informacije_o_zahtevu>
        <zzs:Razlog>Neki razlog</zzs:Razlog>
        <zzs:Mesto>Novi Sad</zzs:Mesto>
        <zzs:Datum_izdavanja property="pred:datum" datatype="xs:date">2021-05-04</zzs:Datum_izdavanja>
    </zzs:Informacije_o_zahtevu>
</zzs:zahtev>

=== matkoman-py/xml-veb-servisi/VaccinationApplication/src/main/resources/static/xsd/ZahtevZelenogSertifikata.xml
<?xml version="1.0" encoding="UTF-8"?>
<zzs:zahtev about="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zzs="http://www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata" xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata ZahtevZelenogSertifikata.xsd ">
  <zzs:Podnosilac_zahteva>
    <zzs:Ime_i_prezime datatype="xs:string" property="pred:ime_i_prezime">zzs:Ime_i_prezime</zzs:Ime_i_prezime>
    <zzs:Datum_rodjenja>2001-01-01</zzs:Datum_rodjenja>
    <zzs:Pol>Musko</zzs:Pol>
    <zzs:Jedinstveni_maticni_broj_gradjana datatype="xs:string" property="pred:jmbg">zzs:Jedinstveni_maticni_broj_gradjana</zzs:Jedinstveni_maticni_broj_gradjana>
    <zzs:Broj_pasosa datatype="xs:string" property="pred:broj_pasosa">zzs:Broj_pasosa</zzs:Broj_pasosa>
  </zzs:Podnosilac_zahteva>
  <zzs:Informacije_o_zahtevu>
    <zzs:Razlog>zzs:Razlog</zzs:Razlog>
    <zzs:Mesto>zzs:Mesto</zzs:Mesto>
    <zzs:Datum_izdavanja datatype="xs:date" property="pred:datum_izdavanja">2001-01-01</zzs:Datum_izdavanja>
  </zzs:Informacije_o_zahtevu>
</zzs:zahtev>

=== matkoman-py/xml-veb-servisi/KT1/XMLSeme/ZahtevZelenogSertifikata.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev xmlns="www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.ftn.uns.ac.rs/zahtev_zelenog_sertifikata file:/C:/Users/aleks/Desktop/PROGRAMIRANJE/FAKS/CETVRTA%20GODINA/XML/ZahtevZelenogSertifikata.xsd">
    <Podnosilac_zahteva>
        <Ime_i_prezime>Ime_i_prezime0</Ime_i_prezime>
        <Datum_rodjenja>2006-05-04</Datum_rodjenja>
        <Pol>Musko</Pol>
        <Jedinstveni_maticni_broj_gradjana>0000000000000</Jedinstveni_maticni_broj_gradjana>
        <Broj_pasosa>0000000000</Broj_pasosa>
    </Podnosilac_zahteva>
    <Informacije_o_zahtevu>
        <Razlog>Razlog0</Razlog>
        <Mesto>Mesto0</Mesto>
        <Datum_izdavanja>2006-05-04</Datum_izdavanja>
    </Informacije_o_zahtevu>
</zahtev>
